/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CheckupReport = IDL.Record({
  'id' : IDL.Text,
  'visitDate' : IDL.Text,
  'notes' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const DoctorGuidance = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'treatment' : IDL.Text,
  'notes' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Frequency = IDL.Variant({
  'twiceDaily' : IDL.Null,
  'daily' : IDL.Null,
  'asNeeded' : IDL.Null,
  'weekly' : IDL.Null,
});
export const MedicineReminder = IDL.Record({
  'id' : IDL.Text,
  'times' : IDL.Vec(IDL.Text),
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'isActive' : IDL.Bool,
  'notes' : IDL.Text,
  'frequency' : Frequency,
});
export const DoseStatus = IDL.Variant({
  'taken' : IDL.Null,
  'missed' : IDL.Null,
  'snoozed' : IDL.Null,
});
export const DoseLog = IDL.Record({
  'status' : DoseStatus,
  'snoozeMinutes' : IDL.Opt(IDL.Int),
  'reminderId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ReminderDayStats = IDL.Record({
  'missedDoses' : IDL.Nat,
  'reminderId' : IDL.Text,
  'reminderName' : IDL.Text,
  'adherenceRate' : IDL.Float64,
  'takenDoses' : IDL.Nat,
  'snoozedDoses' : IDL.Nat,
  'totalDoses' : IDL.Nat,
});
export const DayStats = IDL.Record({
  'missedDoses' : IDL.Nat,
  'date' : IDL.Text,
  'takenDoses' : IDL.Nat,
  'snoozedDoses' : IDL.Nat,
  'totalDoses' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'photoUrl' : IDL.Text,
  'gender' : IDL.Text,
  'locality' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCheckupReport' : IDL.Func([CheckupReport], [], []),
  'addDoctorGuidance' : IDL.Func([DoctorGuidance], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReminder' : IDL.Func([MedicineReminder], [], []),
  'deleteCheckupReport' : IDL.Func([IDL.Text], [], []),
  'deleteDoctorGuidance' : IDL.Func([IDL.Text], [], []),
  'deleteReminder' : IDL.Func([IDL.Text], [], []),
  'getAllCheckupReports' : IDL.Func([], [IDL.Vec(CheckupReport)], ['query']),
  'getAllDayLogs' : IDL.Func([IDL.Int], [IDL.Vec(DoseLog)], ['query']),
  'getAllDayLogsRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(DoseLog)],
      ['query'],
    ),
  'getAllDoctorGuidance' : IDL.Func([], [IDL.Vec(DoctorGuidance)], ['query']),
  'getAllLogs' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
  'getAllReminderDayStats' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(ReminderDayStats)],
      ['query'],
    ),
  'getAllReminderDayStatsRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(ReminderDayStats)],
      ['query'],
    ),
  'getAllReminderLogs' : IDL.Func([IDL.Text], [IDL.Vec(DoseLog)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(MedicineReminder)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getDayStats' : IDL.Func([IDL.Int], [DayStats], ['query']),
  'getDayStatsRange' : IDL.Func([IDL.Int, IDL.Int], [DayStats], ['query']),
  'getMedicineInfo' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getPastNDayStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Int, DayStats))],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getReminder' : IDL.Func([IDL.Text], [MedicineReminder], ['query']),
  'getReminderDayLogs' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(DoseLog)],
      ['query'],
    ),
  'getReminderDayLogsRange' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(DoseLog)],
      ['query'],
    ),
  'getReminderDayStats' : IDL.Func(
      [IDL.Text, IDL.Int],
      [ReminderDayStats],
      ['query'],
    ),
  'getReminderDayStatsRange' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [ReminderDayStats],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDose' : IDL.Func([DoseLog], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCheckupReport' : IDL.Func([CheckupReport], [], []),
  'updateDoctorGuidance' : IDL.Func([DoctorGuidance], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
  'updateReminder' : IDL.Func([MedicineReminder], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CheckupReport = IDL.Record({
    'id' : IDL.Text,
    'visitDate' : IDL.Text,
    'notes' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const DoctorGuidance = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'treatment' : IDL.Text,
    'notes' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Frequency = IDL.Variant({
    'twiceDaily' : IDL.Null,
    'daily' : IDL.Null,
    'asNeeded' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const MedicineReminder = IDL.Record({
    'id' : IDL.Text,
    'times' : IDL.Vec(IDL.Text),
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'isActive' : IDL.Bool,
    'notes' : IDL.Text,
    'frequency' : Frequency,
  });
  const DoseStatus = IDL.Variant({
    'taken' : IDL.Null,
    'missed' : IDL.Null,
    'snoozed' : IDL.Null,
  });
  const DoseLog = IDL.Record({
    'status' : DoseStatus,
    'snoozeMinutes' : IDL.Opt(IDL.Int),
    'reminderId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ReminderDayStats = IDL.Record({
    'missedDoses' : IDL.Nat,
    'reminderId' : IDL.Text,
    'reminderName' : IDL.Text,
    'adherenceRate' : IDL.Float64,
    'takenDoses' : IDL.Nat,
    'snoozedDoses' : IDL.Nat,
    'totalDoses' : IDL.Nat,
  });
  const DayStats = IDL.Record({
    'missedDoses' : IDL.Nat,
    'date' : IDL.Text,
    'takenDoses' : IDL.Nat,
    'snoozedDoses' : IDL.Nat,
    'totalDoses' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'photoUrl' : IDL.Text,
    'gender' : IDL.Text,
    'locality' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCheckupReport' : IDL.Func([CheckupReport], [], []),
    'addDoctorGuidance' : IDL.Func([DoctorGuidance], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReminder' : IDL.Func([MedicineReminder], [], []),
    'deleteCheckupReport' : IDL.Func([IDL.Text], [], []),
    'deleteDoctorGuidance' : IDL.Func([IDL.Text], [], []),
    'deleteReminder' : IDL.Func([IDL.Text], [], []),
    'getAllCheckupReports' : IDL.Func([], [IDL.Vec(CheckupReport)], ['query']),
    'getAllDayLogs' : IDL.Func([IDL.Int], [IDL.Vec(DoseLog)], ['query']),
    'getAllDayLogsRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(DoseLog)],
        ['query'],
      ),
    'getAllDoctorGuidance' : IDL.Func([], [IDL.Vec(DoctorGuidance)], ['query']),
    'getAllLogs' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
    'getAllReminderDayStats' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(ReminderDayStats)],
        ['query'],
      ),
    'getAllReminderDayStatsRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(ReminderDayStats)],
        ['query'],
      ),
    'getAllReminderLogs' : IDL.Func([IDL.Text], [IDL.Vec(DoseLog)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(MedicineReminder)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getDayStats' : IDL.Func([IDL.Int], [DayStats], ['query']),
    'getDayStatsRange' : IDL.Func([IDL.Int, IDL.Int], [DayStats], ['query']),
    'getMedicineInfo' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getPastNDayStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Int, DayStats))],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getReminder' : IDL.Func([IDL.Text], [MedicineReminder], ['query']),
    'getReminderDayLogs' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(DoseLog)],
        ['query'],
      ),
    'getReminderDayLogsRange' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(DoseLog)],
        ['query'],
      ),
    'getReminderDayStats' : IDL.Func(
        [IDL.Text, IDL.Int],
        [ReminderDayStats],
        ['query'],
      ),
    'getReminderDayStatsRange' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [ReminderDayStats],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDose' : IDL.Func([DoseLog], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCheckupReport' : IDL.Func([CheckupReport], [], []),
    'updateDoctorGuidance' : IDL.Func([DoctorGuidance], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
    'updateReminder' : IDL.Func([MedicineReminder], [], []),
  });
};

export const init = ({ IDL }) => { return []; };