/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayStats {
  'missedDoses' : bigint,
  'date' : string,
  'takenDoses' : bigint,
  'snoozedDoses' : bigint,
  'totalDoses' : bigint,
}
export interface DoseLog {
  'status' : DoseStatus,
  'snoozeMinutes' : [] | [bigint],
  'reminderId' : string,
  'timestamp' : bigint,
}
export type DoseStatus = { 'taken' : null } |
  { 'missed' : null } |
  { 'snoozed' : null };
export type Frequency = { 'twiceDaily' : null } |
  { 'daily' : null } |
  { 'asNeeded' : null } |
  { 'weekly' : null };
export interface MedicineReminder {
  'id' : string,
  'times' : Array<string>,
  'dosage' : string,
  'name' : string,
  'color' : string,
  'isActive' : boolean,
  'notes' : string,
  'frequency' : Frequency,
}
export interface ReminderDayStats {
  'missedDoses' : bigint,
  'reminderId' : string,
  'reminderName' : string,
  'adherenceRate' : number,
  'takenDoses' : bigint,
  'snoozedDoses' : bigint,
  'totalDoses' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReminder' : ActorMethod<[MedicineReminder], undefined>,
  'deleteReminder' : ActorMethod<[string], undefined>,
  'getAllDayLogs' : ActorMethod<[bigint], Array<DoseLog>>,
  'getAllDayLogsRange' : ActorMethod<[bigint, bigint], Array<DoseLog>>,
  'getAllLogs' : ActorMethod<[], Array<DoseLog>>,
  'getAllReminderDayStats' : ActorMethod<[bigint], Array<ReminderDayStats>>,
  'getAllReminderDayStatsRange' : ActorMethod<
    [bigint, bigint],
    Array<ReminderDayStats>
  >,
  'getAllReminderLogs' : ActorMethod<[string], Array<DoseLog>>,
  'getAllReminders' : ActorMethod<[], Array<MedicineReminder>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentStreak' : ActorMethod<[], bigint>,
  'getDayStats' : ActorMethod<[bigint], DayStats>,
  'getDayStatsRange' : ActorMethod<[bigint, bigint], DayStats>,
  'getMedicineInfo' : ActorMethod<[string], string>,
  'getPastNDayStats' : ActorMethod<[bigint], Array<[bigint, DayStats]>>,
  'getReminder' : ActorMethod<[string], MedicineReminder>,
  'getReminderDayLogs' : ActorMethod<[string, bigint], Array<DoseLog>>,
  'getReminderDayLogsRange' : ActorMethod<
    [string, bigint, bigint],
    Array<DoseLog>
  >,
  'getReminderDayStats' : ActorMethod<[string, bigint], ReminderDayStats>,
  'getReminderDayStatsRange' : ActorMethod<
    [string, bigint, bigint],
    ReminderDayStats
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDose' : ActorMethod<[DoseLog], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateReminder' : ActorMethod<[MedicineReminder], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];