/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DoseLog {
    status: DoseStatus;
    snoozeMinutes?: bigint;
    reminderId: string;
    timestamp: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DayStats {
    missedDoses: bigint;
    date: string;
    takenDoses: bigint;
    snoozedDoses: bigint;
    totalDoses: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MedicineReminder {
    id: string;
    times: Array<string>;
    dosage: string;
    name: string;
    color: string;
    isActive: boolean;
    notes: string;
    frequency: Frequency;
}
export interface ReminderDayStats {
    missedDoses: bigint;
    reminderId: string;
    reminderName: string;
    adherenceRate: number;
    takenDoses: bigint;
    snoozedDoses: bigint;
    totalDoses: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum DoseStatus {
    taken = "taken",
    missed = "missed",
    snoozed = "snoozed"
}
export enum Frequency {
    twiceDaily = "twiceDaily",
    daily = "daily",
    asNeeded = "asNeeded",
    weekly = "weekly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReminder(reminder: MedicineReminder): Promise<void>;
    deleteReminder(reminderId: string): Promise<void>;
    getAllDayLogs(dayStartNS: bigint): Promise<Array<DoseLog>>;
    getAllDayLogsRange(startTimeNS: bigint, endTimeNS: bigint): Promise<Array<DoseLog>>;
    getAllLogs(): Promise<Array<DoseLog>>;
    getAllReminderDayStats(dayStartNS: bigint): Promise<Array<ReminderDayStats>>;
    getAllReminderDayStatsRange(startTimeNS: bigint, endTimeNS: bigint): Promise<Array<ReminderDayStats>>;
    getAllReminderLogs(reminderId: string): Promise<Array<DoseLog>>;
    getAllReminders(): Promise<Array<MedicineReminder>>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentStreak(): Promise<bigint>;
    getDayStats(dayStartNS: bigint): Promise<DayStats>;
    getDayStatsRange(startTimeNS: bigint, endTimeNS: bigint): Promise<DayStats>;
    getMedicineInfo(brandName: string): Promise<string>;
    getPastNDayStats(nDays: bigint): Promise<Array<[bigint, DayStats]>>;
    getReminder(reminderId: string): Promise<MedicineReminder>;
    getReminderDayLogs(reminderId: string, dayStartNS: bigint): Promise<Array<DoseLog>>;
    getReminderDayLogsRange(reminderId: string, startTimeNS: bigint, endTimeNS: bigint): Promise<Array<DoseLog>>;
    getReminderDayStats(reminderId: string, dayStartNS: bigint): Promise<ReminderDayStats>;
    getReminderDayStatsRange(reminderId: string, startTimeNS: bigint, endTimeNS: bigint): Promise<ReminderDayStats>;
    isCallerAdmin(): Promise<boolean>;
    logDose(doseLog: DoseLog): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateReminder(reminder: MedicineReminder): Promise<void>;
}
import type { DoseLog as _DoseLog, DoseStatus as _DoseStatus, Frequency as _Frequency, MedicineReminder as _MedicineReminder, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReminder(arg0: MedicineReminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(to_candid_MedicineReminder_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(to_candid_MedicineReminder_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteReminder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async getAllDayLogs(arg0: bigint): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDayLogs(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDayLogs(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDayLogsRange(arg0: bigint, arg1: bigint): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDayLogsRange(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDayLogsRange(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLogs(): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReminderDayStats(arg0: bigint): Promise<Array<ReminderDayStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminderDayStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminderDayStats(arg0);
            return result;
        }
    }
    async getAllReminderDayStatsRange(arg0: bigint, arg1: bigint): Promise<Array<ReminderDayStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminderDayStatsRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminderDayStatsRange(arg0, arg1);
            return result;
        }
    }
    async getAllReminderLogs(arg0: string): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminderLogs(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminderLogs(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReminders(): Promise<Array<MedicineReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminders();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminders();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentStreak();
            return result;
        }
    }
    async getDayStats(arg0: bigint): Promise<DayStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayStats(arg0);
            return result;
        }
    }
    async getDayStatsRange(arg0: bigint, arg1: bigint): Promise<DayStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayStatsRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayStatsRange(arg0, arg1);
            return result;
        }
    }
    async getMedicineInfo(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicineInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicineInfo(arg0);
            return result;
        }
    }
    async getPastNDayStats(arg0: bigint): Promise<Array<[bigint, DayStats]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPastNDayStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPastNDayStats(arg0);
            return result;
        }
    }
    async getReminder(arg0: string): Promise<MedicineReminder> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminder(arg0);
                return from_candid_MedicineReminder_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminder(arg0);
            return from_candid_MedicineReminder_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminderDayLogs(arg0: string, arg1: bigint): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderDayLogs(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderDayLogs(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminderDayLogsRange(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderDayLogsRange(arg0, arg1, arg2);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderDayLogsRange(arg0, arg1, arg2);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminderDayStats(arg0: string, arg1: bigint): Promise<ReminderDayStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderDayStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderDayStats(arg0, arg1);
            return result;
        }
    }
    async getReminderDayStatsRange(arg0: string, arg1: bigint, arg2: bigint): Promise<ReminderDayStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderDayStatsRange(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderDayStatsRange(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logDose(arg0: DoseLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDose(to_candid_DoseLog_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDose(to_candid_DoseLog_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateReminder(arg0: MedicineReminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(to_candid_MedicineReminder_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(to_candid_MedicineReminder_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DoseLog_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoseLog): DoseLog {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DoseStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoseStatus): DoseStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Frequency_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frequency): Frequency {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MedicineReminder_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicineReminder): MedicineReminder {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    times: Array<string>;
    dosage: string;
    name: string;
    color: string;
    isActive: boolean;
    notes: string;
    frequency: _Frequency;
}): {
    id: string;
    times: Array<string>;
    dosage: string;
    name: string;
    color: string;
    isActive: boolean;
    notes: string;
    frequency: Frequency;
} {
    return {
        id: value.id,
        times: value.times,
        dosage: value.dosage,
        name: value.name,
        color: value.color,
        isActive: value.isActive,
        notes: value.notes,
        frequency: from_candid_Frequency_n16(_uploadFile, _downloadFile, value.frequency)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DoseStatus;
    snoozeMinutes: [] | [bigint];
    reminderId: string;
    timestamp: bigint;
}): {
    status: DoseStatus;
    snoozeMinutes?: bigint;
    reminderId: string;
    timestamp: bigint;
} {
    return {
        status: from_candid_DoseStatus_n10(_uploadFile, _downloadFile, value.status),
        snoozeMinutes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.snoozeMinutes)),
        reminderId: value.reminderId,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taken: null;
} | {
    missed: null;
} | {
    snoozed: null;
}): DoseStatus {
    return "taken" in value ? DoseStatus.taken : "missed" in value ? DoseStatus.missed : "snoozed" in value ? DoseStatus.snoozed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twiceDaily: null;
} | {
    daily: null;
} | {
    asNeeded: null;
} | {
    weekly: null;
}): Frequency {
    return "twiceDaily" in value ? Frequency.twiceDaily : "daily" in value ? Frequency.daily : "asNeeded" in value ? Frequency.asNeeded : "weekly" in value ? Frequency.weekly : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicineReminder>): Array<MedicineReminder> {
    return value.map((x)=>from_candid_MedicineReminder_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoseLog>): Array<DoseLog> {
    return value.map((x)=>from_candid_DoseLog_n8(_uploadFile, _downloadFile, x));
}
function to_candid_DoseLog_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoseLog): _DoseLog {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_DoseStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoseStatus): _DoseStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Frequency_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_MedicineReminder_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicineReminder): _MedicineReminder {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: DoseStatus;
    snoozeMinutes?: bigint;
    reminderId: string;
    timestamp: bigint;
}): {
    status: _DoseStatus;
    snoozeMinutes: [] | [bigint];
    reminderId: string;
    timestamp: bigint;
} {
    return {
        status: to_candid_DoseStatus_n22(_uploadFile, _downloadFile, value.status),
        snoozeMinutes: value.snoozeMinutes ? candid_some(value.snoozeMinutes) : candid_none(),
        reminderId: value.reminderId,
        timestamp: value.timestamp
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    times: Array<string>;
    dosage: string;
    name: string;
    color: string;
    isActive: boolean;
    notes: string;
    frequency: Frequency;
}): {
    id: string;
    times: Array<string>;
    dosage: string;
    name: string;
    color: string;
    isActive: boolean;
    notes: string;
    frequency: _Frequency;
} {
    return {
        id: value.id,
        times: value.times,
        dosage: value.dosage,
        name: value.name,
        color: value.color,
        isActive: value.isActive,
        notes: value.notes,
        frequency: to_candid_Frequency_n5(_uploadFile, _downloadFile, value.frequency)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoseStatus): {
    taken: null;
} | {
    missed: null;
} | {
    snoozed: null;
} {
    return value == DoseStatus.taken ? {
        taken: null
    } : value == DoseStatus.missed ? {
        missed: null
    } : value == DoseStatus.snoozed ? {
        snoozed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): {
    twiceDaily: null;
} | {
    daily: null;
} | {
    asNeeded: null;
} | {
    weekly: null;
} {
    return value == Frequency.twiceDaily ? {
        twiceDaily: null
    } : value == Frequency.daily ? {
        daily: null
    } : value == Frequency.asNeeded ? {
        asNeeded: null
    } : value == Frequency.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
